"""Adjust name table 

Revision ID: 6c84023cf044
Revises: b27dbee3935f
Create Date: 2024-08-24 22:54:19.390967

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c84023cf044'
down_revision: Union[str, None] = 'b27dbee3935f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('is_bent', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_router')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_router',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_bent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], name='product_router_delivery_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_router_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_router_pkey')
    )
    op.drop_table('product_delivery')
    # ### end Alembic commands ###
